sonar.projectKey=kinetix-backend
sonar.projectName=Kinetix backend
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.14

sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**,migrations/**

sonar.exclusions=**/__pycache__/**,.venv/**,htmlcov/**,.scannerwork/**
